
project_id = "mjufryrwcedazffgxbws"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.validate-booking-limits]
verify_jwt = false
